from flask_babel import lazy_gettext as _l


def build_links(paraules):
    for i, p in paraules.items():
        desc = p["desc"]
        if "[[" in desc:
            desc_list = desc.split("[[")
            rebuilt = []
            for segment in desc_list:
                if "]]" in segment:
                    link, rest = segment.split("]]")
                    link_text, link_num = link.split("|")
                    rebuilt.append("<span class='desc-link pointer' onclick='load_word(" + link_num + ")'>" + link_text + "</span>")
                    rebuilt.append(rest)
                else:
                    rebuilt.append(segment)
            paraules[i]["desc"] = "".join(rebuilt)
    return paraules


def build_words():
    words_by_topic = {}
    for i, word in build_links(paraules).items():
        temas = word.get("temas", [])
        if temas:
            for tema in temas:
                if tema not in words_by_topic:
                    words_by_topic[tema] = {"name": temas_list.get(tema, {}).get("name", "(" + tema + ")"), "contents": {}}
                words_by_topic[tema]["contents"][i] = word
        else:
            if "none" not in words_by_topic:
                words_by_topic["none"] = {"name": "Sin Tema", "contents": {}}
            words_by_topic["none"]["contents"][i] = word
    return words_by_topic


temas_list = {
    "POL": {"name": _l("Política")},
    "ECON": {"name": _l("Economía")},
    "ECOL": {"name": _l("Ecología")},
    "TEC": {"name": _l("Tecnología")},
    "ESTAD": {"name": _l("Estadística")},
    "ANT": {"name": _l("Antropología")},
    "FIS": {"name": _l("Física")},
    "SAL": {"name": _l("Salud")},
    "PSI": {"name": _l("Psicología")},
    "ART": {"name": _l("Arte")},
    "BIO": {"name": _l("Biología")},
    "URB": {"name": _l("Urbanismo")},
    "CIE": {"name": _l("Ciencia")},
}



paraules = {
    1: {"temas": ["POL"], "name": _l("Ventana de Overton"), "desc": _l("<p>Conjunto de ideas políticas que se consideran 'aceptables' en la sociedad en general y, por tanto, que pueden acabar convirtiéndose en leyes.</p>Las ideas más aceptadas están en el centro de la ventana, las que son algo más atrevidas están en los bordes, y las más radicales están fuera de la ventana. La ventana se mueve con el tiempo a medida que la opinión pública cambia, ya sea de forma natural o porque personas o partidos influyentes (y dispuestos a aceptar las reprimiendas) eligen repetir las ideas radicales hasta que el público se acostumbra a ellas."), "url": {"wiki": _l("https://es.wikipedia.org/wiki/Ventana_de_Overton")}},
    2: {"temas": ["POL"], "name": _l("Radical vs Extremista"), "desc": _l("<p>Usamos las dos palabras como si fueran equivalentes, pero la etimología nos da dos matices distintos.</p><p><b>Radical</b> es alguien dispuesto a cambiar las cosas de raíz. <b>Extremista</b> es alguien dispuesto a llevar las cosas al extremo.</p><i>Por ejemplo, querer que la vivienda sea gratis para todo el mundo no es 'Extrema Izquierda', es 'Izquierda Radical'. 'Extrema Izquierda' sería por ejemplo torturar a los milmillonarios hasta que acepten dejar de serlo.</i>")},
    3: {"temas": ["POL"], "name": _l("Índice de la Dignidad"), "desc": _l("El <b>Índice de la Dignidad</b> (en inglés <i>Dignity Index</i>) es una escala que mide el grado de humanidad con el que los discursos hablan de otras personas. Va del 1 al 8, y es muy útil para detectar pronto la polarización y la deriva que lleva al <b>Alto conflicto</b>."), "urls": {"web": "https://www.dignity.us/"}},
    4: {"temas": ["POL"], "name": _l("Emprendedores del Conflicto"), "desc": _l("Aquellas personas que se benefician del [[Alto Conflicto|9]] y que eligen deliberadamente provocarlo y alimentarlo."), "cred": _l("Acuñado por Amanda Ripley en su (recomendadísimo) libro <i>High Conflict: Why We Get Trapped and How We Get Out</i>")},
    5: {"temas": ["POL"], "name": _l("La regla del 3.5%"), "desc": _l("<p>Siempre que un <b>3.5% de la población</b> ha protestado de manera <b>noviolenta</b> contra un gobierno autoritario, el gobierno autoritario ha caído.</p>Es decir, para provocar un cambio en el mundo siempre hace falta mucha menos gente de la que parece.")},
    6: {"temas": ["POL"], "name": _l("El propósito de un sistema es aquello que hace"), "desc": _l("<p>(En inglés <b>POSIWID</b>, <i>The purpose of a system is what it does</i>)<br>Es la idea de que no tiene sentido juzgar un sistema en función de las supuestas intenciones de sus creadores o promotores si a la hora de la verdad constantemente consigue o provoca otros resultados.</p>Si algo siempre 'funciona mal' y nadie lo corrige, es sensato asumir que la intención real es que funcione mal.")},
    7: {"temas": ["POL"], "name": _l("Los ricos te quieren racista"), "desc": _l("<p>Si dividimos la sociedad entre <i>Gente muy rica</i> y <i>Gente normal</i>, la gente muy rica es muy poca gente, y la gente normal somos muchísimos. Cuando los más ricos acumulan tantísimo dinero, lo lógico sería que la gente normal se pusiera de acuerdo para recuperarlo, porque son muchísimos más y ganarían fácilmente.</p>La escapatoria que tienen los ricos para que eso no pase, es conseguir <b>dividir a la gente normal</b> para que se peleen. Por eso les es tan útil el racismo, la homofobia, la misoginia, etc. Los ricos te quieren racista, porque saben que si no nos odiamos somos más.")},
    8: {"temas": ["POL"], "name": _l("Guerra jurídica"), "desc": _l("<p>En inglés <i>Lawfare</i>. Es cuando se usa el poder y favor de los jueces de forma abusiva o ilegal para intentar eliminar oponentes, ya sea inhabilitándoles o simplemente dañando su reputación al hacer que parezca que sus problemas con la justicia son legítimos.</p>En general acaba siendo <b>judicial y mediática</b> e implicando cuatro actores: las <b>organizaciones</b> que ponen denuncias falsas, los <b>jueces corruptos</b> que las aceptan sin pruebas, los <b>medios de comunicación</b> que aprovechan para provocar revuelo, y las <b>cuentas en redes sociales</b> que amplifican esas noticias falsas o esos casos judiciales ilegítimos.")},
    9: {"temas": ["POL"], "name": _l("Alto Conflicto"), "desc": "Conflicto en el que ya no hay espacio para la curiosidad porque la polarización y el [[tribalismo|11]] lo han invadido todo.<br>Estadio de los conflictos, opuesto al <b>Conflicto Sano</b>, en el que las cosas sólo empeoran para las dos partes, porque ambas están más preocupadas por <i>ganar</i> y <i>humillar</i> que por resolver el problema subyacente.", "cred": _l("Acuñado por Amanda Ripley en su (recomendadísimo) libro <i>High Conflict: Why We Get Trapped and How We Get Out</i>")},
    10: {"temas": ["POL"], "name": _l("Appartheid"), "desc": _l("Sistema político en el que las propias instituciones y leyes separan y discriminan a las personas en función de su raza.")},
    11: {"temas": ["POL"], "name": _l("Tribalismo"), "desc": _l("<p>Dinámica en la que las personas se identifican con un grupo y sienten una fuerte lealtad hacia ese grupo, favoreciéndolo frente a los demás y a menudo excluyendo o discriminando a los miembros de los demás grupos.</p><i>Lo que pasa, por ejemplo, con los seguidores de equipos de fútbol, o con los votantes que defienden a 'su' partido haga lo que haga.</i>")},
    12: {"temas": ["POL"], "name": "Intervencionismo de EUA", "desc": ""},
    13: {"temas": ["POL"], "name": _l("Sanciones de EUA"), "desc": _l("<p>Bloqueos económicos que los Estados Unidos imponen a países, entidades o personas para intentar controlarlos por la fuerza.</p><p>Si una persona no hace lo que los estados unidos quieren, el gobierno de los EUA puede bloquearle sus cuentas bancarias para que no pueda pagar nada con ellas ni sacar dinero de ellas (o como mínimo prohibirle a las empresas estadounidenses que hagan negocios con ella). Si un país no hace lo que EUA quiere, pueden impedir que ese país use el dólar en sus transacciones y forzar a los demás países a no hacer negocios con él.</p><p>Todo esto suena a que sólo tendrían que poder hacerlo dentro de sus fronteras, pero el dólar americano está tan metido de lleno en la economía internacional que incluso cuando dos países sin dólar hacen negocios, hay dólares de por medio (es como el idioma inglés, pero en versión moneda). Así pues, los países (y personas) se ven forzados a seguirle el rollo a los EUA o, si no les da la gana, pagar las consecuencias y quedar aislados del resto del mundo. Además, incluso si esos países sancionados encontraran maneras de no usar dólares, los que hicieran negocio con ellos se arriesgarían a recibir sus propias sanciones (sanciones <i>secundarias</i>) como represalia por no haberse añadido a la decisión de los EUA.</p>Evidentemente, una herramienta como esta se podría usar para el bien (para aislar a los gobiernos que provoquen guerras o atenten contra los derechos humanos), pero está claro que Estados Unidos las usa para otras cosas diametralmente opuestas."), "cred": _l("Algunos ejemplos de esto son el bloqueo comercial con el que los EUA lleva décadas estrangulando a Cuba en un intento desesperado de poder decir que 'el comunismo no funciona', o el bloqueo que han hecho de las cuentas bancarias (y de la posibilidad de viajar en avión) de Francesca Albanese y los varios representantes de la Corte Penal Internacional que se atrevieron a condenar a Netanyahu y decir en voz alta que lo que está haciendo es un genocidio.")},  # i.e. Albanese &

    16: {"temas": ["POL"], "name": "Quién elige qué es 'Terrorismo'", "desc": ""},  # i.e. surveilance & bibi changes
    17: {"temas": ["POL"], "name": _l("Los Archivos de Epstein"), "desc": _l("<p>Una colección descomunalmente grande de pruebas que demuestran que los hombres más ricos del mundo se han pasado años quedando en una isla privada con el objetivo explícito de cometer auténticas barbaridades, como <b>violar a menores</b>, <b>matar personas</b> o <b>comer carne humana</b>. Todo eso dejando de lado lo obvio, que es que también les servía para tejer influencias y controlar el mundo.</p>Esos archivos <b>los ha tenido la FBI durante décadas</b>, hablan de gente como Donald Trump y Elon Musk, y saber que existen es quizás la prueba más obvia de que la justicia no es igual para todos, porque hasta ahora nadie se ha molestado en empezar a detener a los monstruos que aparecen en ellos. Sí detuvieron al propietario de la isla, pero curiosamente 'se suicidó' un día que fallaron las dos cámaras de su celda.")},
    18: {"temas": ["POL"], "name": "Lo que sea que pasa con el CGPJ", "desc": "", "hide": True},
    19: {"temas": ["POL"], "name": _l("Gerrymandering"), "desc": _l("<p>Cambiar las fronteras de las circunscripciones electorales de manera maliciosa para intentar favorecer o perjudicar a un partido o grupo de personas.</p><i>Por ejemplo, dividir a los votantes de un partido en muchos sectores distintos para que no ganen representación en ninguno de ellos, o amontonarlos de manera excesiva en un sólo distrito para que no les sobre suficiente gente como para ganar en ninguno de los demás.</i>")},  # "<p>Canviar les fronteres de les circumscripcions electorals de manera maliciosa per intentar afavorir o perjudicar a un partit o grup de persones.</p><i>Per exemple, dividir els votants d'un partit en molts sectors diferents per tal que no guanyin representació a cap d'ells, o apilonar-los de manera excessiva en un sol sector per tal que no els sobri prou gent per guanyar a cap dels altres.</i>"
    20: {"temas": ["POL"], "name": "La gente no sabe cuándo no se muere", "desc": ""},  # ft. hank
    21: {"temas": ["POL"], "name": _l("Terrorismo estocástico"), "desc": _l("<p>La manera como repetir discursos hostiles públicamente acaba desencadenando en violencia impartida por personas anónimas (incluso si no se les pide explícitamente que sean violentas), simplemente por probabilidad.</p>El modo en el que los actores que quieren dañar a ciertos grupos de personas no necesitan pedir violencia explícitamente ni cometerla ellos mismos, porque saben que si señalan y siembran suficiente odio, alguien entre el público acabará decidiendo cometerla por su cuenta.")},
    22: {"temas": ["POL"], "name": _l("Abya Yala"), "desc": _l("Nombre con el que se refieren al continente americano las culturas indígenas que habitan en él y muchos movimientos sociales. Se plantea como alternativa a términos como <b>América</b> o <b>Nuevo mundo</b>, que fueron impuestos por los colonizadores europeos.")},
    23: {"temas": ["POL"], "name": _l("Sionismo"), "desc": _l("<p>Movimiento político que dice que los judíos deberían tener su propio país (un país religioso judio), y que ese país tiene que crearse a base de robarle las tierras al país de Palestina, expulsando de ellas a los palestinos que puedan haber estado viviendo en ellas.</p><p>Evidentemente, ser judío <b>no tiene nada que ver</b> con apoyar algo así, pero a los sionistas les gusta fingir que si estás en contra del sionismo es porque odias a los judíos. De hecho, haber sido víctimas del genocidio Nazi les está sirviendo como la excusa ideal para conseguir que nadie se atreva a pararles los pies ahora que han decidido cometer uno ellos mismos.</p>")},
    24: {"temas": ["POL", "ECON"], "name": _l("Pinkwashing"), "desc": _l("Tácticas publicitarias en las que las empresas y gobiernos posan como aliadas del colectivo LGBT+ para intentar parecer progresistas.")},
    25: {"temas": ["POL"], "name": _l("Interseccionalidad"), "desc": _l("<p>La idea de que no podemos analizar las injusticias sociales de modo aislado, sino que hay que tener en cuenta cómo se afectan entre ellas, porque cada persona o conjunto de personas tendrá su combinación única de discriminaciones y privilegios en función de los grupos sociales a los que pertenezca.</p><i>Por ejemplo, es <b>Feminismo Interseccional</b> aquél que se preocupa por incluír y dar la misma voz a todas las mujeres (i.e. no sólo a las blancas, cristianas, cis...), y por entender y solidarizarse con las causas por las que éstas puedan estar luchando en paralelo a la feminista.</i>")},
    26: {"temas": ["POL"], "name": "Las guerras tienen normativa", "desc": ""},
    27: {"temas": ["POL"], "name": "Externalización de fronteras", "desc": ""},
    28: {"temas": ["POL"], "name": _l("Okupación vs Allanamiento de Morada"), "desc": _l("<p>Cuando una persona entra en una casa que no es suya, hay dos delitos profundamente distintos que podría estar cometiendo. Si entra en una casa que se usa para vivir (incluso en segundas residencias) el delito es <b>Allanamiento de morada</b>. Si entra en una casa abandonada (que no se usa para vivir) el delito es <b>Usurpación</b> (que es lo que llamamos Okupación).</p>Esa idea de que '<i>si tardas a darte cuenta, los Okupas se pueden quedar y tienes que ir a juicio</i>' es sólo para Okupación. Si alguien se mete en una casa <b>en la que vives</b>, le echan al momento y sin juicio. Es decir, los Okupas <b>no pueden</b> meterse en tu casa (pero a los medios de comunicación, empresas de alarmas y políticos de derechas les interesa que parezca que sí, porque el miedo les da visitas, ventas y votos).")},
    29: {"temas": ["POL"], "name": _l("Sur Global"), "desc": _l("Conjunto de países en proceso de industrializarse o recientemente industrializados (no necesariamente todos en el hemisferio sur), muchos de ellos víctimas del (neo)colonialismo. Se adopta como una alternativa menos discriminatoria a términos obsoletos como <i>Tercer Mundo</i>.")},
    30: {"temas": ["POL"], "name": _l("Reaccionario"), "desc": _l("Que se opone a los cambios políticos progressistas o innovadores, y que intenta deshacerlos si ya estaban hechos.")},
    31: {"temas": ["POL"], "name": "Polarización", "desc": ""},
    32: {"temas": ["POL"], "name": "Europa no es un continente", "desc": ""},
    33: {"temas": ["ECON"], "name": "Tener dinero da dinero", "desc": ""},
    34: {"temas": ["ECON", "TEC"], "name": _l("Obsolescencia Programada"), "desc": _l("<p>La manera como las empresas diseñan los productos para que se estropeen al cabo de cierto tiempo (p.ej. cuando se acabe la garantía) en lugar de diseñarlos para que duren el máximo, porque saben que si duran demasiado no venderán tantos. La manera como rediseñan deliberadamente los productos para conseguir que duren menos, o incluso programan su código informático para que finjan haberse estropeado al cabo de cierto tiempo.</p>"), "cred": _l("Hay un documental muy interesante al respecto, que se llama <i>Comprar, Tirar, Comprar</i>.")},
    35: {"temas": ["ECON"], "name": _l("Economía de rosquilla"), "desc": _l("<p>Sistema para analizar la medida en la que la economía consigue cubrir las necesidades y derechos sociales sin traspasar los límites planetarios que ponen en riesgo la sostenibilidad.</p>La parte más característica del sistema es un diagrama muy visual con forma de anillo que tiene barras hacia dentro indicando la medida en la que la sociedad está fracasando a la hora de cubrir cada una de las necesidades humanas, y barras hacia fuera indicando la medida en la que la sociedad está sobrepasando cada uno de los límites ecológicos.")},
    36: {"temas": ["ECON"], "name": "El PIB no funciona", "desc": _l("<p>Solemos usar el PIB (el <i>Producto Interior Bruto</i>) como si fuera un indicador de cómo de bien van las cosas en un país: damos por supuesto que cuanto más PIB tenga, mejor le tienen que estar yendo las cosas. Pero la realidad es que el PIB <b>sube</b> con muchas cosas que son <b>malas</b>, y <b>no sube</b> con muchas cosas que son <b>buenas</b>, así que es absurdo usarlo como referencia para saber si el país está haciendo las cosas bien.</p><p>El PIB básicamente lo que hace es medir cuánto se está moviendo el dinero dentro del país, sin importar si el dinero se está moviendo para hacer cosas buenas o cosas malas (y sin notar las cosas que hacemos que mejoran el mundo sin mover dinero). O, dicho de otro modo: un accidente de tren sube el PIB (porque pagamos reparaciones, médicos y funerales). Un ataque terrorista, un terremoto, un derrame de petróleo... todo son cosas que suben el PIB, porque hay que mover dinero para limpiar, curar y reconstruir las casas. También lo suben el contrabando, el negocio de las drogas, las casas de apuestas y la prostitución. Y en cambio, no sube el PIB cuando dejas de trabajar para cuidar tú mismo a tus hijos. Baja el PIB si las renovables nos ayudan a generar electricidad más barata. Baja el PIB si conseguimos que haya más paz y menos crimen. O si fabricamos y vendemos menos armas. Y, además, no mide de ningún modo si el dinero se usa para cosas sostenibles y, incluso en la parte de medir dinero, ni siquiera mide si está bien repartido o si sólo lo tienen los más ricos.</p>Por todo esto, muchas entidades promueven que se sustituya por otros indicadores mejor diseñados, como el Human Development Index (HDI), el Better Life Index (BLI) o el Genuine Progress Indicator (GPI). Por otro lado, existen marcos de análisis muy interesantes que ponen en primer plano los límites planetarios, como la [[Economía de rosquilla|35]].")},
    37: {"temas": ["ECON"], "name": "Right to Repair", "desc": ""},
    38: {"temas": ["ECON"], "name": "Neocolonialismo", "desc": ""},
    39: {"temas": ["ECON"], "name": _l("Monopolio y Monopsonio"), "desc": _l("Un <b>Monopolio</b> es cuando sólo hay un vendedor para un producto dado. Un <b>Monopsonio</b> es cuando sólo hay un comprador.")},
    40: {"temas": ["ECON"], "name": _l("Mierdificación"), "desc": _l("<p>La <i>decadencia de plataformas</i> o <b>Mierdificación</b> (en inglés <i>Enshittification</i>), es la manera en la que las redes sociales (y demás plataformas online similares) se destruyen a sí mismas persiguiendo cada vez más beneficios. Concretamente, siguen el siguiente ciclo en cuatro fases: primero tratan muy bien a los usuarios (para crecer), luego abusan de sus usuarios para favorecer a las empresas que ganan dinero en la plataforma (por ejemplo los anunciantes), luego abusan también de esas empresas para intentar quedarse todo el dinero para ellas, y finalmente mueren.</p>El ejemplo obvio es la cantidad de anuncios en redes sociales, pero uno de los ejemplos más sonados al respecto es que Google ahora busca peor que antes, porque se dieron cuenta de que si encuentras las cosas a la primera no ves tantos anuncios.")},
    41: {"temas": ["ECON"], "name": _l("Reduflación"), "desc": _l("En inglés <i>Shrinkflation</i>, es el modo en el que las empresas suben el precio de las cosas a base de mantener el precio del producto pero reducir su tamaño o cantidad de producto.")},
    42: {"temas": ["ECON"], "name": "Dynamic Pricing", "desc": ""},
    43: {"temas": ["ECON"], "name": "Paradoja de Jevon", "desc": ""},
    45: {"temas": ["ECON"], "name": "MLM", "desc": ""},
    46: {"temas": ["ECON"], "name": "Economía de la Atención", "desc": ""},
    47: {"temas": ["ECON"], "name": "Extractivismo", "desc": ""},
    48: {"temas": ["ECON", "POL"], "name": _l("Curva de Laffer"), "desc": _l("<p>Relación entre el <b>porcentaje de impuestos</b> que se le exige a los ricos y la <b>recaudación</b> que se puede conseguir con ese porcentaje, suponiendo que esos ricos se pudieran llevar sus riquezas a otros países si el porcentaje sube más de lo que están dispuestos a soportar.</p><p>La idea es que la <b>máxima recaudación</b> ocurre en un punto por el medio entre <i>'Poco porcentaje pero hay muchos ricos'</i> y <i>'Mucho porcentaje pero quedan pocos ricos'</i>. El modelo es criticablemente simple, pero los análisis empíricos dicen que la mayoría de los países están <b>por debajo</b> del punto óptimo (i.e. que les valdría la pena subir el impuesto a los ricos <i>incluso</i> si eso hace que una parte de ellos se vayan).")},
    49: {"temas": ["ECON"], "name": "Better Life Index", "desc": ""},
    50: {"temas": ["ECON", "POL"], "name": "Violencia Simbólica", "desc": ""},  # la historia la escriben los vencedores y la ambición la escriben los opresores
    51: {"temas": ["ECOL"], "name": _l("Puntos de Inflexión"), "desc": _l("<p>A medida que el cambio climático se va acentuando, los distintos sistemas del planeta que hasta ahora eran estables van a ir llegando al límite de lo que pueden aguantar sin desbordar. Esos límites que provocan el desborde se llaman <b>Puntos de Inflexión</b> (en inglés <i>Tipping Points</i>), y son muy importantes porque cruzarlos provocaría cambios drásticos (y a menudo irreversibles), y en muchos casos hace que el cambio climático se acelere a sí mismo (por ejemplo, si se empieza a fundir el hielo de los polos, eso liberará metano que calentará aún más el planeta).</p>"), "cred": _l("Un libro muy interesante que explora estas ideas en detalle es <i>El Ministerio del Futuro</i>, de <i>Kim Stanley Robinson</i>. Ha envejecido extremadamente mal en su optimismo hacia las criptomonedas, pero el resto del libro es profundamente (y de hecho, cada vez más) vigente.")},
    52: {"temas": ["ECOL"], "name": "Temperatura de Bulbo Húmedo", "desc": ""},
    53: {"temas": ["ECOL"], "name": "NIMBY", "desc": ""},
    54: {"temas": ["ECOL"], "name": "Self-Organized Criticality", "desc": ""},  # ft els incendis s'apaguen a l'hivern
    55: {"temas": ["ECOL"], "name": "Greenwashing", "desc": "Tácticas publicitarias orientadas a que empresas, productos y conceptos parezcan sostenibles a pesar de no serlo. Desde anuncios de petroleras llenos de montañas verdes hasta la sutileza de llamarle <i>Gas Natural</i> al metano para que parezca que no es un combustible fósil."},  # e.g. Gas 'Natural'
    57: {"temas": ["ECOL"], "name": "Semillas con derechos de autor", "desc": ""},
    58: {"temas": ["ECOL"], "name": "La trampa de la fruta sin pepitas", "desc": ""},
    59: {"temas": ["ECOL"], "name": "Ciclo de vida del producto", "desc": ""},

    71: {"temas": ["TEC"], "name": "FOSS", "desc": _l("<p>En inglés, <i>Free Open Source Software</i>, son programas informáticos gratuitos y de código abierto. Es decir, programas gratis que además tienen el código informático público para que cualquiera pueda comprobar cómo es e incluso copiarlo para hacerse su propia versión.</p>En general los crean y mejoran voluntarios, y probablemente sean la única escapatoria a la [[Mierdificación|40]].")},
    72: {"temas": ["TEC"], "name": "KISS", "desc": ""},
    74: {"temas": ["TEC"], "name": "Alineamento de los Mesa-objectivos", "desc": ""},
    75: {"temas": ["TEC"], "name": "Las empresas de IA trituran llibros únicos", "desc": ""},
    76: {"temas": ["TEC"], "name": "Una máquina de adivinar palabras", "desc": ""},
    77: {"temas": ["TEC"], "name": "Creador vs Influencer", "desc": ""},
    78: {"temas": ["TEC"], "name": "Graceful degradation", "desc": _l("Filosofía de diseño que consiste en preparar a los productos para que cuando se les estropee alguna parte <b>puedan seguir funcionando</b> aunque sea en peores condiciones. Por ejemplo, productos que funcionan más despacio si no tienen todas las baterías, o que te permiten usar las funciones que siguen intactas incluso si hay otras funciones que están rotas (en lugar de dejar de funcionar del todo).")},
    79: {"temas": ["TEC"], "name": _l("Colapso de modelos"), "desc": _l("<p>La manera como las IA generativas van perdiendo cada vez más diversidad y precisión en sus respuestas a medida que usan respuestas generadas por IA para entrenar. La manera como sus propias creaciones, volcadas en internet, hacen que <b>cada vez aprendan peor</b>. Y la manera como son incapaces de mejorar si tienen que aprender de sí mismas.</p>Es este, por otro lado, el motivo principal por el que las empresas de IA están empezando a marcar sus creaciones de maneras imperceptibles. No es porque les haya entrado un ataque de altruismo y quieren que todos podamos distinguir la realidad de la ficción, es sólo porque les da miedo ir a robar contenido de internet y que el contenido robado para entrenar no sea humano.")},

    81: {"temas": ["ESTAD"], "name": "Correlación vs Causalidad", "desc": ""},
    82: {"temas": ["ESTAD"], "name": _l("Ley de los números realmente grandes"), "desc": _l("La idea de que en realidad es probable encontrarte con las cosas improbables siempre y cuando tu muestra sea lo suficientemente grande. Es decir, que si hay los suficientes ejemplos de algo, las cosas más raras que podrían pasar habrán pasado por pura casualidad.")},

    91: {"temas": ["ANT"], "name": "Los buenos ganan si están conectados", "desc": ""},  # ft veritasium
    92: {"temas": ["ANT"], "name": _l("Comunicación No Violenta"), "desc": _l("A menudo abreviado <b>CNV</b>, es un conjunto de técnicas que sirven para hablar de temas potencialmente conflictivos desde el respeto y sin que la persona con la que hablas se ponga a la defensiva."), "cred": _l("Desarrolladas por <i>Marshall Rosenberg</i> en su (recomendadísimo) libro <i>Comunicación No Violenta: Un Lenguaje de Vida</i>.")},
    93: {"temas": ["ANT"], "name": "Game Theory", "desc": ""},

    101: {"temas": ["FIS"], "name": "El universo tiene píxeles", "desc": ""},
    102: {"temas": ["FIS"], "name": _l("La paradoja de Fermi"), "desc": _l("<p>En el universo observable hay una cantidad descomunal de galaxias, con una cantidad descomunal de estrellas cada una, y con unos cuantos planetas cada estrella. La <b>paradoja de Fermi</b> es la idea de que incluso si es muy difícil que esos planetas sean habitables, e incluso si es extremadamente dificil que aparezca vida en ellos, hay tanta y tanta cantidad que por [[la ley de los números realmente grandes|82]] lo normal sería que a estas alturas ya hubiéramos encontrado alguna otra civilización (pero que en cambio no parece que haya ninguna).</p><p>La paradoja es especialmente inquietante porque parece que quiere decir que: o bien es mucho más difícil de lo que creíamos llegar al nivel de desarrollo que tenemos los humanos ahora, o bien hay algún obstáculo desconocido (un <b>Gran Filtro</b>) que hace que sea muy difícil sobrevivir a largo plazo por mucho que hayas llegado a donde hemos llegado hasta ahora. Porque sería muy muy raro que justo fuéramos los primeros.</p>")},
    103: {"temas": ["FIS"], "name": "La cosa está más cerca cuando vas corriendo", "desc": ""},
    104: {"temas": ["FIS"], "name": "El tiempo pasa más lento en el Everest", "desc": ""},
    105: {"temas": ["FIS"], "name": "Acción", "desc": ""},  # m·v·d

    111: {"temas": ["SAL"], "name": _l("Violencia Obstérica"), "desc": _l("La violencia en el trato de las mujeres durante los partos. Desde darles un trato deshumanizador, hasta cosas como aplicarles procedimientos innecesarios e intrusivos sin su consentimiento sólo para poder acelerar el parto.")},
    112: {"temas": ["SAL"], "name": "Endometrosis", "desc": ""},
    113: {"temas": ["SAL"], "name": "La medicina se basa en el cuerpo de los hombres", "desc": ""},
    114: {"temas": ["SAL"], "name": "El primer Crash Test Dummy femenino", "desc": ""},
    115: {"temas": ["SAL"], "name": _l("Placebo y Nocebo"), "desc": _l("El <b>Efecto Placebo</b> es cuando tu salud mejora al tomarte una medicina falsa (que no hace nada) sólo porque creías que era verdadera y que te iba a ir bien. El <b>Efecto Nocebo</b> es la otra cara de la moneda: cuando tu salud empeora al tomarte una sustancia que no hace nada sólo porque creías que el tratamiento te iba a sentar mal.")},
    117: {"temas": ["SAL"], "name": _l("Homeopatía"), "desc": _l("La superstición que dice que puedes fabricar el antídoto para un veneno a base de mezclar ese mismo veneno con tantísima agua que al final sólo te queda agua.")},
    118: {"temas": ["SAL"], "name": _l("Psicosomático"), "desc": _l("Que tiene su origen en la mente pero tiene efectos sobre el cuerpo. Por ejemplo, cuando el estrés y la ansiedad provocan (o empeoran) los síntomas de una enfermedad física.")},

    121: {"temas": ["PSI"], "name": "Freud se lo patillaba todo", "desc": ""},
    122: {"temas": ["PSI"], "name": "Sesgo de supervivencia", "desc": ""},
    123: {"temas": ["PSI"], "name": "Sesgo de confirmación", "desc": ""},
    124: {"temas": ["PSI"], "name": "Sesgo de autoridad", "desc": ""},
    125: {"temas": ["PSI"], "name": "El enneagrama no funciona", "desc": ""},
    126: {"temas": ["PSI"], "name": "Big 5", "desc": ""},
    127: {"temas": ["PSI"], "name": "Cuando pusimos a prueba los astrólogos", "desc": ""},
    128: {"temas": ["PSI"], "name": "Flow", "desc": ""},  # ft czickszentmihalyi
    129: {"temas": ["PSI"], "name": "Dunning-Krugger", "desc": ""},
    130: {"temas": ["PSI"], "name": "Sesgo de disponibilidad", "desc": ""},
    131: {"temas": ["ANT"], "name": _l("Meme"), "desc": _l("<p><b>Elemento de la cultura</b> o del comportamiento <b>que se transmite por imitación</b> entre personas o entre generaciones. O dicho de otro modo, los <i>memes</i> técnicamente son el equivalente cultural a la idea biológica de los <i>genes</i>.</p>Luego por extensión hemos acabado llamando 'memes' sobre todo a las imágenes graciosas de internet, pero la definición técnica incluye también cosas como <i>darse la mano para saludarse</i>."), "cred": _l("La palabra, acuñada por Richard Dawkins, es una mezcla entre 'gen' y la misma raíz griega que significa 'imitar' en palabras como 'mimo' o 'mímica'.")},
    132: {"temas": ["PSI"], "name": "White Savior Complex", "desc": ""},
    133: {"temas": ["PSI"], "name": "Autotélico vs Heterotélico", "desc": ""},
    134: {"temas": ["PSI"], "name": _l("Saliencia"), "desc": _l("La facilidad que tiene algo para destacar sobre lo demás. Especialmente relevante en la [[Economía de la Atención|46]].")},
    135: {"temas": ["PSI"], "name": _l("Saturación semántica"), "desc": _l("<p>Cuando una palabra <b>deja de tener sentido</b> para ti durante un rato sólo porque <b>la has dicho demasiadas veces</b> y ahora te suena ajena.</p>Pasa porque <i>usar demasiadas veces seguidas</i> las neuronas encargadas de recordar el significado de una palabra acaba provocando que <i>se cansen</i> y durante un rato no sean capaces de ayudarte a entenderla.")},

    141: {"temas": ["ART"], "name": _l("Si el autor cobra, no podemos separarlo de la obra"), "desc": _l("<p>Uno de los grandes debates del arte es si se puede o no se puede <i>separar el autor de la obra</i>. Es decir, si es válido y moralmente correcto disfrutar de una obra de arte sabiendo que su autor ha cometido actos que no lo eran. Ese debate, si bien es posible con autores como Wagner (que ya no va a cobrar nada de sus obras porque está muerto y sus derechos de autor caducados), no tiene sentido con los autores contemporáneos, porque cualquier consumo que hagamos de sus obras va a ir directamente a sus bolsillos.</p>Seguramente el ejemplo más claro de eso actualmente es <b>J.K.Rowling</b>, que literalmente usa los ingresos que gana con los derechos de autor de <i>Harry Potter</i> para <b>hacerle la vida imposible a la comunidad trans</b>, financiando leyes y organizaciones anti-trans en el Reino Unido (y, de hecho, se pasea por las redes chuleando de que lo hace). En casos así, la obra es inseparable, y es imposible consumirla éticamente."), "cred": _l("Para los potterheads que se acaban de llevar un chasco (o que ya lo sabían y llevan tiempo gestionando el duelo), me dicen por ahí que <i>Nevermoor</i>, de la autora queer (y vocalmente anti-transfobia) <i>Jessica Townsend</i> tiene un vibe muy parecido!")},  # ft rowling
    142: {"temas": ["ART"], "name": _l("Espacio negativo"), "desc": _l("Forma que tiene el espacio vacío que hay entre los objetos, especialmente cuando da lugar a siluetas interesantes.")},
    143: {"temas": ["ART"], "name": "Kerning", "desc": _l("<p>Conjunto de pequeñas correcciones que se le hace a la distancia entre los distintos pares de letras con la intención de conseguir que todos los espacios entre letra y letra parezcan igual de anchos.</p>Por ejemplo, la manera como la 'o' de 'To' se esconde debajo de la 'T' aprovechando que sobraría espacio. ")},

    151: {"temas": ["BIO"], "name": _l("Pez no significa nada"), "desc": _l("<p>En biología, la palabra 'pez' no es ninguna categoría: si quieres recortar un trozo del árbol de las especies que incluya a los tiburones y también a las sardinas, entonces ese grupo de especies también te va a incluír a tí.</p>O dicho de otro modo, los humanos somos más família de los peces que los peces de los tiburones, así que 'pez' es como mucho una palabra del mundo de la cocina. En lo que es estrictamente biología, o no existen los peces, o tú también eres un pez.")},
    152: {"temas": ["BIO"], "name": "Els ocells són dinosaures", "desc": ""},
    153: {"temas": ["POL"], "name": "Poder blando", "desc": ""},

    160: {"temas": ["URB"], "name": _l("Camino del Deseo"), "desc": _l("Camino que se forma de manera natural en las zonas de hierba cuando muchas personas distintas se salen de la ruta preestablecida con la intención de tomar el mismo atajo.")},
    161: {"temas": ["POL"], "name": "Golpe blando", "desc": ""},
    162: {"temas": ["ANT"], "name": "Cultura de la violación", "desc": ""},
    163: {"temas": ["ART"], "name": "Test de Bechdel", "desc": _l("Prueba sencilla que podemos usar para analizar las creaciones artísticas narrativas (típicamente las películas) si queremos delatar cómo de exagerada es en algunas de ellas la falta de representación femenina. Para superar la prueba, la narración tiene que cumplir tres requisitos: que <b>aparezcan dos mujeres</b>, que ambas <b>tengan nombre</b>, y que <b>hablen entre ellas sobre algo que no sea un hombre</b>.")},
    164: {"temas": ["ART"], "name": _l("Arma de Chéjov"), "desc": _l("<p>En inglés, <b>Chekhov's gun</b>, es la idea de que todos los elementos de las narraciones tienen que ser necesarios o, si no lo son, deberían ser eliminados.</p>Por ejemplo, que si hay una pistola colgada en la pared en el primer acto, en algun momento alguien tiene que dispararla. Porque si no la va a disparar nadie ni va a pasar nada con ella, haber explicado que está ahí sólo consigue distraer (y frustrar) a la audiencia.")},
    165: {"temas": ["SAL"], "name": _l("Vacunas mRNA"), "desc": _l("Tecnología de vacunación que consiste en darles a las células de tu cuerpo una receta de cómo fabricar una de las piezas del virus, para que así sean tus propias células las que le preparan a tu sistema inmune los ejemplos con los que entrenar.")},
    166: {"temas": ["ANT"], "name": "Máximas de Grice", "desc": ""},
    167: {"temas": ["CIE"], "name": _l("Navaja de Ockham"), "desc": _l("<p>La idea de que en igualdad de condiciones e igualdad de pruebas, la explicación más simple tiene más probabilidades de ser verdad.</p>Es decir, la idea de que la ciencia tiene que intentar siempre explicar las cosas del modo más simple posible, y que sólo vale añadir complejidad si no hay otras maneras más sencillas de entender los mismos resultados.")},
    168: {"temas": ["POL"], "name": "Tecnocracia", "desc": ""},
    169: {"temas": ["POL"], "name": "Malicious Compliance", "desc": ""},
    170: {"temas": ["POL"], "name": "Weaponized Incompetence", "desc": ""},
    171: {"temas": ["POL"], "name": "Guerra Híbrida", "desc": ""},
    172: {"temas": ["SAL"], "name": "El Càncer no és una malaltia", "desc": ""},
    173: {"temas": ["ECON"], "name": "Paper Towns", "desc": ""},
    174: {"temas": ["SAL"], "name": "Neoantígen", "desc": ""},

}
